//{
//"isSuccessful": true,
//"hasContent": true,
//"code": 200,
//"message": null,
//"detailed_error": null,
//"data": {
//"current_page": 1,
//"data": [
//{
//"id": 4,
//"mobile_phone": "+963936997540",
//"photo_path": null,
//"name": "louai alkhdr",
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 46,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": null,
//"storage_video_path": null,
//"user_id": 4,
//"is_photo": 1,
//"is_video": 0,
//"photo_path": "http://res.cloudinary.com/djooohujg/image/upload/v1695986109/1695986108.jpg",
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 47,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1695986153/1695986151.mp4",
//"storage_video_path": null,
//"user_id": 4,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 16,
//"mobile_phone": "+96399887766",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 48,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1695986280/1695986274.mp4",
//"storage_video_path": null,
//"user_id": 16,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 49,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": null,
//"storage_video_path": null,
//"user_id": 16,
//"is_photo": 1,
//"is_video": 0,
//"photo_path": "http://res.cloudinary.com/djooohujg/image/upload/v1695986326/1695986324.jpg",
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 50,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": null,
//"storage_video_path": null,
//"user_id": 16,
//"is_photo": 1,
//"is_video": 0,
//"photo_path": "http://res.cloudinary.com/djooohujg/image/upload/v1695986354/1695986353.jpg",
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 17,
//"mobile_phone": "+963998877952",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 51,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": null,
//"storage_video_path": null,
//"user_id": 17,
//"is_photo": 1,
//"is_video": 0,
//"photo_path": "http://res.cloudinary.com/djooohujg/image/upload/v1695986420/1695986419.jpg",
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 52,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": null,
//"storage_video_path": null,
//"user_id": 17,
//"is_photo": 1,
//"is_video": 0,
//"photo_path": "http://res.cloudinary.com/djooohujg/image/upload/v1695986444/1695986442.jpg",
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 18,
//"mobile_phone": "+963998877950",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 53,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": null,
//"storage_video_path": null,
//"user_id": 18,
//"is_photo": 1,
//"is_video": 0,
//"photo_path": "http://res.cloudinary.com/djooohujg/image/upload/v1695986510/1695986508.jpg",
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 54,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1695986575/1695986574.mp4",
//"storage_video_path": null,
//"user_id": 18,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 19,
//"mobile_phone": "+963986652116",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 55,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696157793/1696157791.mp4",
//"storage_video_path": null,
//"user_id": 19,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 56,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696157839/1696157836.mp4",
//"storage_video_path": null,
//"user_id": 19,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 57,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696157888/1696157881.mp4",
//"storage_video_path": null,
//"user_id": 19,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 58,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696157923/1696157921.mp4",
//"storage_video_path": null,
//"user_id": 19,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 59,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696157962/1696157960.mp4",
//"storage_video_path": null,
//"user_id": 19,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 20,
//"mobile_phone": "+963991992630",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 60,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158001/1696157999.mp4",
//"storage_video_path": null,
//"user_id": 20,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 61,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158076/1696158074.mp4",
//"storage_video_path": null,
//"user_id": 20,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 62,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158103/1696158101.mp4",
//"storage_video_path": null,
//"user_id": 20,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 63,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158145/1696158142.mp4",
//"storage_video_path": null,
//"user_id": 20,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 64,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158200/1696158197.mp4",
//"storage_video_path": null,
//"user_id": 20,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 21,
//"mobile_phone": "+963991992552",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 65,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158320/1696158318.mp4",
//"storage_video_path": null,
//"user_id": 21,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 66,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158346/1696158344.mp4",
//"storage_video_path": null,
//"user_id": 21,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 67,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158378/1696158376.mp4",
//"storage_video_path": null,
//"user_id": 21,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 22,
//"mobile_phone": "+963991992951",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 68,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158431/1696158429.mp4",
//"storage_video_path": null,
//"user_id": 22,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 69,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158482/1696158480.mp4",
//"storage_video_path": null,
//"user_id": 22,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 70,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158525/1696158522.mp4",
//"storage_video_path": null,
//"user_id": 22,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 23,
//"mobile_phone": "+963992882951",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 71,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158569/1696158567.mp4",
//"storage_video_path": null,
//"user_id": 23,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 72,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158616/1696158614.mp4",
//"storage_video_path": null,
//"user_id": 23,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 73,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158659/1696158656.mp4",
//"storage_video_path": null,
//"user_id": 23,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//},
//{
//"id": 24,
//"mobile_phone": "+963992732951",
//"photo_path": null,
//"name": null,
//"username": null,
//"original_user_id": null,
//"email": null,
//"stories": [
//{
//"id": 74,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158701/1696158698.mp4",
//"storage_video_path": null,
//"user_id": 24,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//},
//{
//"id": 75,
//"cut_video_name": null,
//"cut_video_path": null,
//"full_video_name": null,
//"full_video_path": "http://res.cloudinary.com/djooohujg/video/upload/v1696158731/1696158729.mp4",
//"storage_video_path": null,
//"user_id": 24,
//"is_photo": 0,
//"is_video": 1,
//"photo_path": null,
//"file": null,
//"is_seen": false,
//"viewers_count": 0,
//"media": []
//}
//],
//"media": []
//}
//],
//"first_page_url": "http://stories_staging.trydos.tech/stories/public/api/v1/stories/users_stories?page=1",
//"from": 1,
//"last_page": 2,
//"last_page_url": "http://stories_staging.trydos.tech/stories/public/api/v1/stories/users_stories?page=2",
//"links": [
//{
//"url": null,
//"label": "&laquo; Previous",
//"active": false
//},
//{
//"url": "http://stories_staging.trydos.tech/stories/public/api/v1/stories/users_stories?page=1",
//"label": "1",
//"active": true
//},
//{
//"url": "http://stories_staging.trydos.tech/stories/public/api/v1/stories/users_stories?page=2",
//"label": "2",
//"active": false
//},
//{
//"url": "http://stories_staging.trydos.tech/stories/public/api/v1/stories/users_stories?page=2",
//"label": "Next &raquo;",
//"active": false
//}
//],
//"next_page_url": "http://stories_staging.trydos.tech/stories/public/api/v1/stories/users_stories?page=2",
//"path": "http://stories_staging.trydos.tech/stories/public/api/v1/stories/users_stories",
//"per_page": 10,
//"prev_page_url": null,
//"to": 10,
//"total": 12
//}
//}