// Mocks generated by Mockito 5.4.4 from annotations
// in trydos/test/test_auth/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i33;
import 'dart:io' as _i41;

import 'package:bloc/bloc.dart' as _i46;
import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i13;
import 'package:flutter/material.dart' as _i44;
import 'package:logger/logger.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i15;
import 'package:trydos/core/di/di_container.dart' as _i45;
import 'package:trydos/core/domin/repositories/prefs_repository.dart' as _i16;
import 'package:trydos/core/error/failures.dart' as _i34;
import 'package:trydos/core/use_case/use_case.dart' as _i43;
import 'package:trydos/features/authentication/data/data_sources/auth_remote_datasource.dart'
    as _i35;
import 'package:trydos/features/authentication/data/models/create_user_response_model.dart'
    as _i5;
import 'package:trydos/features/authentication/data/models/get_user_country_response_model.dart'
    as _i8;
import 'package:trydos/features/authentication/data/models/login_to_chat_response_model.dart'
    as _i3;
import 'package:trydos/features/authentication/data/models/login_to_stories_response_model.dart'
    as _i10;
import 'package:trydos/features/authentication/data/models/send_otp_response_model.dart'
    as _i6;
import 'package:trydos/features/authentication/data/models/store_fcm_token_response_model.dart'
    as _i4;
import 'package:trydos/features/authentication/data/models/verify_guest_phone_response_model.dart'
    as _i9;
import 'package:trydos/features/authentication/data/models/verify_otp_sign_up_and_in_response_model.dart'
    as _i7;
import 'package:trydos/features/authentication/domain/repositories/auth_repository.dart'
    as _i12;
import 'package:trydos/features/authentication/domain/use_cases/create_user_usecase.dart'
    as _i20;
import 'package:trydos/features/authentication/domain/use_cases/get_customer_info_usecase.dart'
    as _i28;
import 'package:trydos/features/authentication/domain/use_cases/get_user_country_usecase.dart'
    as _i29;
import 'package:trydos/features/authentication/domain/use_cases/login_to_chat_usecase.dart'
    as _i17;
import 'package:trydos/features/authentication/domain/use_cases/login_to_market_usecase.dart'
    as _i18;
import 'package:trydos/features/authentication/domain/use_cases/login_to_stories_usecase.dart'
    as _i19;
import 'package:trydos/features/authentication/domain/use_cases/register_guest_usecase.dart'
    as _i26;
import 'package:trydos/features/authentication/domain/use_cases/send_otp_usecase.dart'
    as _i22;
import 'package:trydos/features/authentication/domain/use_cases/store_fcm_usecase.dart'
    as _i21;
import 'package:trydos/features/authentication/domain/use_cases/update_chat_user_name_usecase.dart'
    as _i31;
import 'package:trydos/features/authentication/domain/use_cases/update_name_usecase.dart'
    as _i27;
import 'package:trydos/features/authentication/domain/use_cases/update_stories_user_usecase.dart'
    as _i30;
import 'package:trydos/features/authentication/domain/use_cases/verify_guest_phone_usecase.dart'
    as _i25;
import 'package:trydos/features/authentication/domain/use_cases/verify_otp_signin_usecase.dart'
    as _i23;
import 'package:trydos/features/authentication/domain/use_cases/verify_otp_signup_usecase.dart'
    as _i24;
import 'package:trydos/features/authentication/presentation/manager/auth_bloc.dart'
    as _i32;
import 'package:trydos/features/chat/data/models/change_chat_property_model.dart'
    as _i36;
import 'package:trydos/features/chat/data/models/ImageDetail.dart' as _i40;
import 'package:trydos/features/chat/data/models/media_count.dart' as _i42;
import 'package:trydos/features/chat/data/models/my_chats_response_model.dart'
    as _i38;
import 'package:trydos/features/chat/data/models/my_contacts_response_model.dart'
    as _i39;
import 'package:trydos/features/chat/data/models/upload_file_response_model.dart'
    as _i37;
import 'package:trydos/features/chat/domain/repositories/chat_repository.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginToChatResponseModel_1 extends _i1.SmartFake
    implements _i3.LoginToChatResponseModel {
  _FakeLoginToChatResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoreFcmTokenResponseModel_2 extends _i1.SmartFake
    implements _i4.StoreFcmTokenResponseModel {
  _FakeStoreFcmTokenResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateUserResponseModel_3 extends _i1.SmartFake
    implements _i5.CreateUserResponseModel {
  _FakeCreateUserResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSendOtpResponseModel_4 extends _i1.SmartFake
    implements _i6.SendOtpResponseModel {
  _FakeSendOtpResponseModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyOtpSignUpAndInResponseModel_5 extends _i1.SmartFake
    implements _i7.VerifyOtpSignUpAndInResponseModel {
  _FakeVerifyOtpSignUpAndInResponseModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_6 extends _i1.SmartFake implements _i7.User {
  _FakeUser_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetUserCountryResponseModel_7 extends _i1.SmartFake
    implements _i8.GetUserCountryResponseModel {
  _FakeGetUserCountryResponseModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyGuestPhoneResponseModel_8 extends _i1.SmartFake
    implements _i9.VerifyGuestPhoneResponseModel {
  _FakeVerifyGuestPhoneResponseModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginToStoriesResponseModel_9 extends _i1.SmartFake
    implements _i10.LoginToStoriesResponseModel {
  _FakeLoginToStoriesResponseModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatRepository_10 extends _i1.SmartFake
    implements _i11.ChatRepository {
  _FakeChatRepository_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRepository_11 extends _i1.SmartFake
    implements _i12.AuthRepository {
  _FakeAuthRepository_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_12 extends _i1.SmartFake implements _i13.BaseOptions {
  _FakeBaseOptions_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_13 extends _i1.SmartFake implements _i14.Logger {
  _FakeLogger_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_14 extends _i1.SmartFake
    implements _i15.SharedPreferences {
  _FakeSharedPreferences_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrefsRepository_15 extends _i1.SmartFake
    implements _i16.PrefsRepository {
  _FakePrefsRepository_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_16 extends _i1.SmartFake implements _i13.Dio {
  _FakeDio_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginToChatUseCase_17 extends _i1.SmartFake
    implements _i17.LoginToChatUseCase {
  _FakeLoginToChatUseCase_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginToMarketUseCase_18 extends _i1.SmartFake
    implements _i18.LoginToMarketUseCase {
  _FakeLoginToMarketUseCase_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginToStoriesUseCase_19 extends _i1.SmartFake
    implements _i19.LoginToStoriesUseCase {
  _FakeLoginToStoriesUseCase_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateUserUseCase_20 extends _i1.SmartFake
    implements _i20.CreateUserUseCase {
  _FakeCreateUserUseCase_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoreFcmUseCase_21 extends _i1.SmartFake
    implements _i21.StoreFcmUseCase {
  _FakeStoreFcmUseCase_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSendOtpUseCase_22 extends _i1.SmartFake
    implements _i22.SendOtpUseCase {
  _FakeSendOtpUseCase_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyOtpSignInUseCase_23 extends _i1.SmartFake
    implements _i23.VerifyOtpSignInUseCase {
  _FakeVerifyOtpSignInUseCase_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyOtpSignUpUseCase_24 extends _i1.SmartFake
    implements _i24.VerifyOtpSignUpUseCase {
  _FakeVerifyOtpSignUpUseCase_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyGuestPhoneUseCase_25 extends _i1.SmartFake
    implements _i25.VerifyGuestPhoneUseCase {
  _FakeVerifyGuestPhoneUseCase_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterGuestUseCase_26 extends _i1.SmartFake
    implements _i26.RegisterGuestUseCase {
  _FakeRegisterGuestUseCase_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateNameUseCase_27 extends _i1.SmartFake
    implements _i27.UpdateNameUseCase {
  _FakeUpdateNameUseCase_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetCustomerInfoUseCase_28 extends _i1.SmartFake
    implements _i28.GetCustomerInfoUseCase {
  _FakeGetCustomerInfoUseCase_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetUserCountryUseCase_29 extends _i1.SmartFake
    implements _i29.GetUserCountryUseCase {
  _FakeGetUserCountryUseCase_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStoriesUserUseCase_30 extends _i1.SmartFake
    implements _i30.UpdateStoriesUserUseCase {
  _FakeUpdateStoriesUserUseCase_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateChatUserNameUseCase_31 extends _i1.SmartFake
    implements _i31.UpdateChatUserNameUseCase {
  _FakeUpdateChatUserNameUseCase_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthState_32 extends _i1.SmartFake implements _i32.AuthState {
  _FakeAuthState_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i5.CreateUserResponseModel>> createUser(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i5.CreateUserResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i5.CreateUserResponseModel>(
          this,
          Invocation.method(
            #createUser,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i5.CreateUserResponseModel>>);

  @override
  _i33.Future<
      _i2.Either<_i34.Failure, _i3.LoginToChatResponseModel>> loginToChat(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginToChat,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i3.LoginToChatResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i3.LoginToChatResponseModel>(
          this,
          Invocation.method(
            #loginToChat,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i3.LoginToChatResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>
      loginToMarket(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #loginToMarket,
              [params],
            ),
            returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #loginToMarket,
                [params],
              ),
            )),
          ) as _i33.Future<
              _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>
      registerGuest(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #registerGuest,
              [params],
            ),
            returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #registerGuest,
                [params],
              ),
            )),
          ) as _i33.Future<
              _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i10.LoginToStoriesResponseModel>>
      loginToStories(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #loginToStories,
              [params],
            ),
            returnValue: _i33.Future<
                    _i2.Either<_i34.Failure,
                        _i10.LoginToStoriesResponseModel>>.value(
                _FakeEither_0<_i34.Failure, _i10.LoginToStoriesResponseModel>(
              this,
              Invocation.method(
                #loginToStories,
                [params],
              ),
            )),
          ) as _i33.Future<
              _i2.Either<_i34.Failure, _i10.LoginToStoriesResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> updateName(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #updateName,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> updateChatUserName(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatUserName,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #updateChatUserName,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> updateStoriesUser(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStoriesUser,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #updateStoriesUser,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> deleteFcmToken(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFcmToken,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #deleteFcmToken,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i7.User>> getCustomerInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomerInfo,
          [],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, _i7.User>>.value(
            _FakeEither_0<_i34.Failure, _i7.User>(
          this,
          Invocation.method(
            #getCustomerInfo,
            [],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i7.User>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i8.GetUserCountryResponseModel>>
      getUserCountry() => (super.noSuchMethod(
            Invocation.method(
              #getUserCountry,
              [],
            ),
            returnValue: _i33.Future<
                    _i2.Either<_i34.Failure,
                        _i8.GetUserCountryResponseModel>>.value(
                _FakeEither_0<_i34.Failure, _i8.GetUserCountryResponseModel>(
              this,
              Invocation.method(
                #getUserCountry,
                [],
              ),
            )),
          ) as _i33.Future<
              _i2.Either<_i34.Failure, _i8.GetUserCountryResponseModel>>);

  @override
  _i33.Future<
      _i2.Either<_i34.Failure, _i4.StoreFcmTokenResponseModel>> storeFcmToken(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeFcmToken,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i4.StoreFcmTokenResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i4.StoreFcmTokenResponseModel>(
          this,
          Invocation.method(
            #storeFcmToken,
            [params],
          ),
        )),
      ) as _i33
          .Future<_i2.Either<_i34.Failure, _i4.StoreFcmTokenResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i6.SendOtpResponseModel>> sendOtp(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [params],
        ),
        returnValue: _i33
            .Future<_i2.Either<_i34.Failure, _i6.SendOtpResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i6.SendOtpResponseModel>(
          this,
          Invocation.method(
            #sendOtp,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i6.SendOtpResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>
      verifyOtpSignIn(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #verifyOtpSignIn,
              [params],
            ),
            returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #verifyOtpSignIn,
                [params],
              ),
            )),
          ) as _i33.Future<
              _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>
      verifyOtpSignUp(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #verifyOtpSignUp,
              [params],
            ),
            returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #verifyOtpSignUp,
                [params],
              ),
            )),
          ) as _i33.Future<
              _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i9.VerifyGuestPhoneResponseModel>>
      verifyGuestPhone(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #verifyGuestPhone,
              [params],
            ),
            returnValue: _i33.Future<
                    _i2.Either<_i34.Failure,
                        _i9.VerifyGuestPhoneResponseModel>>.value(
                _FakeEither_0<_i34.Failure, _i9.VerifyGuestPhoneResponseModel>(
              this,
              Invocation.method(
                #verifyGuestPhone,
                [params],
              ),
            )),
          ) as _i33.Future<
              _i2.Either<_i34.Failure, _i9.VerifyGuestPhoneResponseModel>>);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i35.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i33.Future<_i3.LoginToChatResponseModel> loginToChat(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginToChat,
          [params],
        ),
        returnValue: _i33.Future<_i3.LoginToChatResponseModel>.value(
            _FakeLoginToChatResponseModel_1(
          this,
          Invocation.method(
            #loginToChat,
            [params],
          ),
        )),
      ) as _i33.Future<_i3.LoginToChatResponseModel>);

  @override
  _i33.Future<bool> deleteFcmToken(Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFcmToken,
          [params],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<_i4.StoreFcmTokenResponseModel> storeFcmToken(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeFcmToken,
          [params],
        ),
        returnValue: _i33.Future<_i4.StoreFcmTokenResponseModel>.value(
            _FakeStoreFcmTokenResponseModel_2(
          this,
          Invocation.method(
            #storeFcmToken,
            [params],
          ),
        )),
      ) as _i33.Future<_i4.StoreFcmTokenResponseModel>);

  @override
  _i33.Future<_i5.CreateUserResponseModel> createUser(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [params],
        ),
        returnValue: _i33.Future<_i5.CreateUserResponseModel>.value(
            _FakeCreateUserResponseModel_3(
          this,
          Invocation.method(
            #createUser,
            [params],
          ),
        )),
      ) as _i33.Future<_i5.CreateUserResponseModel>);

  @override
  _i33.Future<_i6.SendOtpResponseModel> sendOtp(Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [params],
        ),
        returnValue: _i33.Future<_i6.SendOtpResponseModel>.value(
            _FakeSendOtpResponseModel_4(
          this,
          Invocation.method(
            #sendOtp,
            [params],
          ),
        )),
      ) as _i33.Future<_i6.SendOtpResponseModel>);

  @override
  _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel> verifyOtpSignUp(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtpSignUp,
          [params],
        ),
        returnValue: _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>.value(
            _FakeVerifyOtpSignUpAndInResponseModel_5(
          this,
          Invocation.method(
            #verifyOtpSignUp,
            [params],
          ),
        )),
      ) as _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>);

  @override
  _i33.Future<_i7.User> getCustomerInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCustomerInfo,
          [],
        ),
        returnValue: _i33.Future<_i7.User>.value(_FakeUser_6(
          this,
          Invocation.method(
            #getCustomerInfo,
            [],
          ),
        )),
      ) as _i33.Future<_i7.User>);

  @override
  _i33.Future<_i8.GetUserCountryResponseModel> getUserCountry() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCountry,
          [],
        ),
        returnValue: _i33.Future<_i8.GetUserCountryResponseModel>.value(
            _FakeGetUserCountryResponseModel_7(
          this,
          Invocation.method(
            #getUserCountry,
            [],
          ),
        )),
      ) as _i33.Future<_i8.GetUserCountryResponseModel>);

  @override
  _i33.Future<bool> updateName(Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [params],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> updateStoriesUser(Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStoriesUser,
          [params],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> updateChatUserName(Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatUserName,
          [params],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel> verifyOtpSignIn(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtpSignIn,
          [params],
        ),
        returnValue: _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>.value(
            _FakeVerifyOtpSignUpAndInResponseModel_5(
          this,
          Invocation.method(
            #verifyOtpSignIn,
            [params],
          ),
        )),
      ) as _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>);

  @override
  _i33.Future<_i9.VerifyGuestPhoneResponseModel> verifyGuestPhone(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyGuestPhone,
          [params],
        ),
        returnValue: _i33.Future<_i9.VerifyGuestPhoneResponseModel>.value(
            _FakeVerifyGuestPhoneResponseModel_8(
          this,
          Invocation.method(
            #verifyGuestPhone,
            [params],
          ),
        )),
      ) as _i33.Future<_i9.VerifyGuestPhoneResponseModel>);

  @override
  _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel> loginToMarket(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginToMarket,
          [params],
        ),
        returnValue: _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>.value(
            _FakeVerifyOtpSignUpAndInResponseModel_5(
          this,
          Invocation.method(
            #loginToMarket,
            [params],
          ),
        )),
      ) as _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>);

  @override
  _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel> registerGuest(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerGuest,
          [params],
        ),
        returnValue: _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>.value(
            _FakeVerifyOtpSignUpAndInResponseModel_5(
          this,
          Invocation.method(
            #registerGuest,
            [params],
          ),
        )),
      ) as _i33.Future<_i7.VerifyOtpSignUpAndInResponseModel>);

  @override
  _i33.Future<_i10.LoginToStoriesResponseModel> loginToStories(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginToStories,
          [params],
        ),
        returnValue: _i33.Future<_i10.LoginToStoriesResponseModel>.value(
            _FakeLoginToStoriesResponseModel_9(
          this,
          Invocation.method(
            #loginToStories,
            [params],
          ),
        )),
      ) as _i33.Future<_i10.LoginToStoriesResponseModel>);
}

/// A class which mocks [CreateUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUserUseCase extends _i1.Mock implements _i20.CreateUserUseCase {
  MockCreateUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.ChatRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeChatRepository_10(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i11.ChatRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i5.CreateUserResponseModel>> call(
          _i20.CreateUserParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i5.CreateUserResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i5.CreateUserResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i5.CreateUserResponseModel>>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i11.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i36.ChangeChatPropertyModel>>
      changeChatProperty(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #changeChatProperty,
              [params],
            ),
            returnValue: _i33.Future<
                    _i2
                    .Either<_i34.Failure, _i36.ChangeChatPropertyModel>>.value(
                _FakeEither_0<_i34.Failure, _i36.ChangeChatPropertyModel>(
              this,
              Invocation.method(
                #changeChatProperty,
                [params],
              ),
            )),
          ) as _i33
              .Future<_i2.Either<_i34.Failure, _i36.ChangeChatPropertyModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i5.CreateUserResponseModel>> createUser(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i5.CreateUserResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i5.CreateUserResponseModel>(
          this,
          Invocation.method(
            #createUser,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i5.CreateUserResponseModel>>);

  @override
  _i33.Future<
      _i2.Either<_i34.Failure, _i37.UploadFileResponseModel>> uploadFile(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i37.UploadFileResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i37.UploadFileResponseModel>(
          this,
          Invocation.method(
            #uploadFile,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i37.UploadFileResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> saveContacts(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveContacts,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #saveContacts,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, String>> getDateTime() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDateTime,
          [],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, String>>.value(
            _FakeEither_0<_i34.Failure, String>(
          this,
          Invocation.method(
            #getDateTime,
            [],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, String>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i38.Message>> sendMessage(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, _i38.Message>>.value(
            _FakeEither_0<_i34.Failure, _i38.Message>(
          this,
          Invocation.method(
            #sendMessage,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i38.Message>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> readAllMessages(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllMessages,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #readAllMessages,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> receiveMessage(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #receiveMessage,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #receiveMessage,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> deleteChat(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChat,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #deleteChat,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i39.MyContactsResponseModel>>
      getContacts() => (super.noSuchMethod(
            Invocation.method(
              #getContacts,
              [],
            ),
            returnValue: _i33.Future<
                    _i2
                    .Either<_i34.Failure, _i39.MyContactsResponseModel>>.value(
                _FakeEither_0<_i34.Failure, _i39.MyContactsResponseModel>(
              this,
              Invocation.method(
                #getContacts,
                [],
              ),
            )),
          ) as _i33
              .Future<_i2.Either<_i34.Failure, _i39.MyContactsResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i38.MyChatsResponseModel>> getChats(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChats,
          [params],
        ),
        returnValue: _i33
            .Future<_i2.Either<_i34.Failure, _i38.MyChatsResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i38.MyChatsResponseModel>(
          this,
          Invocation.method(
            #getChats,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i38.MyChatsResponseModel>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, List<_i38.Message>>> getMessagesForChat(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesForChat,
          [params],
        ),
        returnValue:
            _i33.Future<_i2.Either<_i34.Failure, List<_i38.Message>>>.value(
                _FakeEither_0<_i34.Failure, List<_i38.Message>>(
          this,
          Invocation.method(
            #getMessagesForChat,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, List<_i38.Message>>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, List<_i38.Message>>> getMessagesBetween(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesBetween,
          [params],
        ),
        returnValue:
            _i33.Future<_i2.Either<_i34.Failure, List<_i38.Message>>>.value(
                _FakeEither_0<_i34.Failure, List<_i38.Message>>(
          this,
          Invocation.method(
            #getMessagesBetween,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, List<_i38.Message>>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i40.ChatImageDetail>>
      loadWidthAndHeight({required _i41.File? file}) => (super.noSuchMethod(
            Invocation.method(
              #loadWidthAndHeight,
              [],
              {#file: file},
            ),
            returnValue: _i33
                .Future<_i2.Either<_i34.Failure, _i40.ChatImageDetail>>.value(
                _FakeEither_0<_i34.Failure, _i40.ChatImageDetail>(
              this,
              Invocation.method(
                #loadWidthAndHeight,
                [],
                {#file: file},
              ),
            )),
          ) as _i33.Future<_i2.Either<_i34.Failure, _i40.ChatImageDetail>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i42.MediaCount>> getMediaCount(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaCount,
          [params],
        ),
        returnValue:
            _i33.Future<_i2.Either<_i34.Failure, _i42.MediaCount>>.value(
                _FakeEither_0<_i34.Failure, _i42.MediaCount>(
          this,
          Invocation.method(
            #getMediaCount,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i42.MediaCount>>);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> SendErrorChatToServer(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #SendErrorChatToServer,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #SendErrorChatToServer,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);
}

/// A class which mocks [UpdateStoriesUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateStoriesUserUseCase extends _i1.Mock
    implements _i30.UpdateStoriesUserUseCase {
  MockUpdateStoriesUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> call(
          _i30.UpdateStoriesUserParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);
}

/// A class which mocks [UpdateChatUserNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateChatUserNameUseCase extends _i1.Mock
    implements _i31.UpdateChatUserNameUseCase {
  MockUpdateChatUserNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> call(
          _i31.UpdateChatUserNameParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);
}

/// A class which mocks [LoginToMarketUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginToMarketUseCase extends _i1.Mock
    implements _i18.LoginToMarketUseCase {
  MockLoginToMarketUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<
      _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>> call(
          _i18.LoginToMarketParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<
          _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);
}

/// A class which mocks [LoginToChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginToChatUseCase extends _i1.Mock
    implements _i17.LoginToChatUseCase {
  MockLoginToChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i3.LoginToChatResponseModel>> call(
          _i17.LoginToChatParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i3.LoginToChatResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i3.LoginToChatResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i3.LoginToChatResponseModel>>);
}

/// A class which mocks [LoginToStoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginToStoriesUseCase extends _i1.Mock
    implements _i19.LoginToStoriesUseCase {
  MockLoginToStoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i10.LoginToStoriesResponseModel>> call(
          _i19.LoginToStoriesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2
                .Either<_i34.Failure, _i10.LoginToStoriesResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i10.LoginToStoriesResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33
          .Future<_i2.Either<_i34.Failure, _i10.LoginToStoriesResponseModel>>);
}

/// A class which mocks [StoreFcmUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreFcmUseCase extends _i1.Mock implements _i21.StoreFcmUseCase {
  MockStoreFcmUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i4.StoreFcmTokenResponseModel>> call(
          _i21.StoreFcmParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure, _i4.StoreFcmTokenResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i4.StoreFcmTokenResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33
          .Future<_i2.Either<_i34.Failure, _i4.StoreFcmTokenResponseModel>>);
}

/// A class which mocks [UpdateNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNameUseCase extends _i1.Mock implements _i27.UpdateNameUseCase {
  MockUpdateNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, bool>> call(
          _i27.UpdateNameParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, bool>>.value(
            _FakeEither_0<_i34.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, bool>>);
}

/// A class which mocks [RegisterGuestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterGuestUseCase extends _i1.Mock
    implements _i26.RegisterGuestUseCase {
  MockRegisterGuestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<
      _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>> call(
          _i26.RegisterGuestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<
          _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);
}

/// A class which mocks [SendOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendOtpUseCase extends _i1.Mock implements _i22.SendOtpUseCase {
  MockSendOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i6.SendOtpResponseModel>> call(
          _i22.SendOtpParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33
            .Future<_i2.Either<_i34.Failure, _i6.SendOtpResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i6.SendOtpResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i6.SendOtpResponseModel>>);
}

/// A class which mocks [GetCustomerInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCustomerInfoUseCase extends _i1.Mock
    implements _i28.GetCustomerInfoUseCase {
  MockGetCustomerInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i7.User>> call(_i43.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<_i2.Either<_i34.Failure, _i7.User>>.value(
            _FakeEither_0<_i34.Failure, _i7.User>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<_i2.Either<_i34.Failure, _i7.User>>);
}

/// A class which mocks [VerifyGuestPhoneUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyGuestPhoneUseCase extends _i1.Mock
    implements _i25.VerifyGuestPhoneUseCase {
  MockVerifyGuestPhoneUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i9.VerifyGuestPhoneResponseModel>> call(
          _i25.VerifyGuestPhoneParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2
                .Either<_i34.Failure, _i9.VerifyGuestPhoneResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i9.VerifyGuestPhoneResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33
          .Future<_i2.Either<_i34.Failure, _i9.VerifyGuestPhoneResponseModel>>);
}

/// A class which mocks [VerifyOtpSignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpSignInUseCase extends _i1.Mock
    implements _i23.VerifyOtpSignInUseCase {
  MockVerifyOtpSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<
      _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>> call(
          _i23.VerifyOtpSignInParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<
          _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);
}

/// A class which mocks [VerifyOtpSignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpSignUpUseCase extends _i1.Mock
    implements _i24.VerifyOtpSignUpUseCase {
  MockVerifyOtpSignUpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<
      _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>> call(
          _i24.VerifyOtpSignUpParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2.Either<_i34.Failure,
                    _i7.VerifyOtpSignUpAndInResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33.Future<
          _i2.Either<_i34.Failure, _i7.VerifyOtpSignUpAndInResponseModel>>);
}

/// A class which mocks [GetUserCountryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserCountryUseCase extends _i1.Mock
    implements _i29.GetUserCountryUseCase {
  MockGetUserCountryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.AuthRepository);

  @override
  _i33.Future<_i2.Either<_i34.Failure, _i8.GetUserCountryResponseModel>> call(
          _i43.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i33.Future<
                _i2
                .Either<_i34.Failure, _i8.GetUserCountryResponseModel>>.value(
            _FakeEither_0<_i34.Failure, _i8.GetUserCountryResponseModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i33
          .Future<_i2.Either<_i34.Failure, _i8.GetUserCountryResponseModel>>);
}

/// A class which mocks [PrefsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefsRepository extends _i1.Mock implements _i16.PrefsRepository {
  MockPrefsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get getFcmTokens => (super.noSuchMethod(
        Invocation.getter(#getFcmTokens),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i44.ThemeMode get getTheme => (super.noSuchMethod(
        Invocation.getter(#getTheme),
        returnValue: _i44.ThemeMode.system,
      ) as _i44.ThemeMode);

  @override
  bool get registeredToChat => (super.noSuchMethod(
        Invocation.getter(#registeredToChat),
        returnValue: false,
      ) as bool);

  @override
  _i33.Future<bool> setVerifiedPhone(bool? verifiedPhone) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVerifiedPhone,
          [verifiedPhone],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setDuration(int? duration) => (super.noSuchMethod(
        Invocation.method(
          #setDuration,
          [duration],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setCountryName(String? countryName) => (super.noSuchMethod(
        Invocation.method(
          #setCountryName,
          [countryName],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setVerificationId(String? verificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVerificationId,
          [verificationId],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setOtpCode(String? otpToken) => (super.noSuchMethod(
        Invocation.method(
          #setOtpCode,
          [otpToken],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setChatToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setChatToken,
          [token],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMarketToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setMarketToken,
          [token],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setStoriesToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setStoriesToken,
          [token],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setServerTime(DateTime? serverTime) => (super.noSuchMethod(
        Invocation.method(
          #setServerTime,
          [serverTime],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMyChatName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setMyChatName,
          [name],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMyStoriesName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setMyStoriesName,
          [name],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMyChatPhoto(String? photo) => (super.noSuchMethod(
        Invocation.method(
          #setMyChatPhoto,
          [photo],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setPhoneNumber(String? phoneNumber) => (super.noSuchMethod(
        Invocation.method(
          #setPhoneNumber,
          [phoneNumber],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<void> setFcmTokenId(int? fcmTokenId) => (super.noSuchMethod(
        Invocation.method(
          #setFcmTokenId,
          [fcmTokenId],
        ),
        returnValue: _i33.Future<void>.value(),
        returnValueForMissingStub: _i33.Future<void>.value(),
      ) as _i33.Future<void>);

  @override
  _i33.Future<bool> setMyChatId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #setMyChatId,
          [id],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMessageFromBackground(String? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMessageFromBackground,
          [message],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setRemovedMessageFromBackground(String? removedMessage) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRemovedMessageFromBackground,
          [removedMessage],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setRemovedChatFromBackground(String? removedChatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRemovedChatFromBackground,
          [removedChatId],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMessageWatchStatusFromBackground(
          String? MessageStatus) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMessageWatchStatusFromBackground,
          [MessageStatus],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMessageReceivedStatusFromBackground(
          String? MessageStatus) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMessageReceivedStatusFromBackground,
          [MessageStatus],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setChatToEditFromBackground(String? chat) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChatToEditFromBackground,
          [chat],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMyStoriesId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #setMyStoriesId,
          [id],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMyMarketId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setMyMarketId,
          [id],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setMyMarketName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setMyMarketName,
          [name],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setCurrentEvent(String? currentEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCurrentEvent,
          [currentEvent],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setTheme(_i44.ThemeMode? themeMode) => (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [themeMode],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> setAFilePathExist(
    String? filePath,
    String? chatId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAFilePathExist,
          [
            filePath,
            chatId,
          ],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeAFilePathExist(
    String? filePath,
    String? chatId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAFilePathExist,
          [
            filePath,
            chatId,
          ],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeAllFilePathExistInChat(String? chatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAllFilePathExistInChat,
          [chatId],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  List<String> getExistenceFiles() => (super.noSuchMethod(
        Invocation.method(
          #getExistenceFiles,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String>? getTheLocalPathForChannel(String? chatId) =>
      (super.noSuchMethod(Invocation.method(
        #getTheLocalPathForChannel,
        [chatId],
      )) as List<String>?);

  @override
  bool isAFilePathExist(
    String? filePath,
    String? chatId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAFilePathExist,
          [
            filePath,
            chatId,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  String? getTheLocalPathForFile(
    String? filePath,
    String? chatId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getTheLocalPathForFile,
        [
          filePath,
          chatId,
        ],
      )) as String?);

  @override
  _i33.Future<bool> addFcmToken(String? fcmToken) => (super.noSuchMethod(
        Invocation.method(
          #addFcmToken,
          [fcmToken],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> clearUser() => (super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeMessageFromBackground() => (super.noSuchMethod(
        Invocation.method(
          #removeMessageFromBackground,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeChatsFromBackground() => (super.noSuchMethod(
        Invocation.method(
          #removeChatsFromBackground,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeRemovedMessageFromBackground() => (super.noSuchMethod(
        Invocation.method(
          #removeRemovedMessageFromBackground,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeMessageWatchStatusFromBackground() =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMessageWatchStatusFromBackground,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeMessageReceivedStatusFromBackground() =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMessageReceivedStatusFromBackground,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> removeChatToEditFromBackground() => (super.noSuchMethod(
        Invocation.method(
          #removeChatToEditFromBackground,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  _i33.Future<bool> clearVerificationId() => (super.noSuchMethod(
        Invocation.method(
          #clearVerificationId,
          [],
        ),
        returnValue: _i33.Future<bool>.value(false),
      ) as _i33.Future<bool>);

  @override
  void saveRequestsData(
    String? url,
    Map<String, dynamic>? response,
    Map<String, dynamic>? headers,
    int? statusCode,
    String? request,
    Map<String, dynamic>? query,
    Map<String, dynamic>? body, {
    String? error,
    String? responseTime,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #saveRequestsData,
          [
            url,
            response,
            headers,
            statusCode,
            request,
            query,
            body,
          ],
          {
            #error: error,
            #responseTime: responseTime,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllRequests() => super.noSuchMethod(
        Invocation.method(
          #clearAllRequests,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeRequestFromCache(Map<String, dynamic>? request) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRequestFromCache,
          [request],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Map<String, dynamic>> getRequestsData() => (super.noSuchMethod(
        Invocation.method(
          #getRequestsData,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);
}

/// A class which mocks [AppModule].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppModule extends _i1.Mock implements _i45.AppModule {
  MockAppModule() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.BaseOptions get dioOption => (super.noSuchMethod(
        Invocation.getter(#dioOption),
        returnValue: _FakeBaseOptions_12(
          this,
          Invocation.getter(#dioOption),
        ),
      ) as _i13.BaseOptions);

  @override
  _i14.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_13(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i14.Logger);

  @override
  _i33.Future<_i15.SharedPreferences> get sharedPreferences =>
      (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue:
            _i33.Future<_i15.SharedPreferences>.value(_FakeSharedPreferences_14(
          this,
          Invocation.getter(#sharedPreferences),
        )),
      ) as _i33.Future<_i15.SharedPreferences>);

  @override
  _i33.Future<_i16.PrefsRepository> get prefsRepository => (super.noSuchMethod(
        Invocation.getter(#prefsRepository),
        returnValue:
            _i33.Future<_i16.PrefsRepository>.value(_FakePrefsRepository_15(
          this,
          Invocation.getter(#prefsRepository),
        )),
      ) as _i33.Future<_i16.PrefsRepository>);

  @override
  _i13.Dio dio(
    _i13.BaseOptions? option,
    _i14.Logger? logger,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #dio,
          [
            option,
            logger,
          ],
        ),
        returnValue: _FakeDio_16(
          this,
          Invocation.method(
            #dio,
            [
              option,
              logger,
            ],
          ),
        ),
      ) as _i13.Dio);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i32.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.LoginToChatUseCase get loginToChatUseCase => (super.noSuchMethod(
        Invocation.getter(#loginToChatUseCase),
        returnValue: _FakeLoginToChatUseCase_17(
          this,
          Invocation.getter(#loginToChatUseCase),
        ),
      ) as _i17.LoginToChatUseCase);

  @override
  _i18.LoginToMarketUseCase get loginToMarketUseCase => (super.noSuchMethod(
        Invocation.getter(#loginToMarketUseCase),
        returnValue: _FakeLoginToMarketUseCase_18(
          this,
          Invocation.getter(#loginToMarketUseCase),
        ),
      ) as _i18.LoginToMarketUseCase);

  @override
  _i19.LoginToStoriesUseCase get loginToStoriesUseCase => (super.noSuchMethod(
        Invocation.getter(#loginToStoriesUseCase),
        returnValue: _FakeLoginToStoriesUseCase_19(
          this,
          Invocation.getter(#loginToStoriesUseCase),
        ),
      ) as _i19.LoginToStoriesUseCase);

  @override
  _i20.CreateUserUseCase get createUserUseCase => (super.noSuchMethod(
        Invocation.getter(#createUserUseCase),
        returnValue: _FakeCreateUserUseCase_20(
          this,
          Invocation.getter(#createUserUseCase),
        ),
      ) as _i20.CreateUserUseCase);

  @override
  _i21.StoreFcmUseCase get storeFcmUseCase => (super.noSuchMethod(
        Invocation.getter(#storeFcmUseCase),
        returnValue: _FakeStoreFcmUseCase_21(
          this,
          Invocation.getter(#storeFcmUseCase),
        ),
      ) as _i21.StoreFcmUseCase);

  @override
  _i22.SendOtpUseCase get sendOtpUseCase => (super.noSuchMethod(
        Invocation.getter(#sendOtpUseCase),
        returnValue: _FakeSendOtpUseCase_22(
          this,
          Invocation.getter(#sendOtpUseCase),
        ),
      ) as _i22.SendOtpUseCase);

  @override
  _i23.VerifyOtpSignInUseCase get verifyOtpSignInUseCase => (super.noSuchMethod(
        Invocation.getter(#verifyOtpSignInUseCase),
        returnValue: _FakeVerifyOtpSignInUseCase_23(
          this,
          Invocation.getter(#verifyOtpSignInUseCase),
        ),
      ) as _i23.VerifyOtpSignInUseCase);

  @override
  _i24.VerifyOtpSignUpUseCase get verifyOtpSignUpUseCase => (super.noSuchMethod(
        Invocation.getter(#verifyOtpSignUpUseCase),
        returnValue: _FakeVerifyOtpSignUpUseCase_24(
          this,
          Invocation.getter(#verifyOtpSignUpUseCase),
        ),
      ) as _i24.VerifyOtpSignUpUseCase);

  @override
  _i25.VerifyGuestPhoneUseCase get verifyGuestPhoneUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#verifyGuestPhoneUseCase),
        returnValue: _FakeVerifyGuestPhoneUseCase_25(
          this,
          Invocation.getter(#verifyGuestPhoneUseCase),
        ),
      ) as _i25.VerifyGuestPhoneUseCase);

  @override
  _i26.RegisterGuestUseCase get registerGuestUseCase => (super.noSuchMethod(
        Invocation.getter(#registerGuestUseCase),
        returnValue: _FakeRegisterGuestUseCase_26(
          this,
          Invocation.getter(#registerGuestUseCase),
        ),
      ) as _i26.RegisterGuestUseCase);

  @override
  _i27.UpdateNameUseCase get updateNameUseCase => (super.noSuchMethod(
        Invocation.getter(#updateNameUseCase),
        returnValue: _FakeUpdateNameUseCase_27(
          this,
          Invocation.getter(#updateNameUseCase),
        ),
      ) as _i27.UpdateNameUseCase);

  @override
  _i28.GetCustomerInfoUseCase get getCustomerInfoUseCase => (super.noSuchMethod(
        Invocation.getter(#getCustomerInfoUseCase),
        returnValue: _FakeGetCustomerInfoUseCase_28(
          this,
          Invocation.getter(#getCustomerInfoUseCase),
        ),
      ) as _i28.GetCustomerInfoUseCase);

  @override
  _i29.GetUserCountryUseCase get getUserCountryUseCase => (super.noSuchMethod(
        Invocation.getter(#getUserCountryUseCase),
        returnValue: _FakeGetUserCountryUseCase_29(
          this,
          Invocation.getter(#getUserCountryUseCase),
        ),
      ) as _i29.GetUserCountryUseCase);

  @override
  _i30.UpdateStoriesUserUseCase get updateStoriesUserUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#updateStoriesUserUseCase),
        returnValue: _FakeUpdateStoriesUserUseCase_30(
          this,
          Invocation.getter(#updateStoriesUserUseCase),
        ),
      ) as _i30.UpdateStoriesUserUseCase);

  @override
  _i31.UpdateChatUserNameUseCase get updateChatUserNameUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#updateChatUserNameUseCase),
        returnValue: _FakeUpdateChatUserNameUseCase_31(
          this,
          Invocation.getter(#updateChatUserNameUseCase),
        ),
      ) as _i31.UpdateChatUserNameUseCase);

  @override
  _i32.AuthState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAuthState_32(
          this,
          Invocation.getter(#state),
        ),
      ) as _i32.AuthState);

  @override
  _i33.Stream<_i32.AuthState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i33.Stream<_i32.AuthState>.empty(),
      ) as _i33.Stream<_i32.AuthState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i32.AuthEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i32.AuthEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i32.AuthState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i32.AuthEvent>(
    _i46.EventHandler<E, _i32.AuthState>? handler, {
    _i46.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i46.Transition<_i32.AuthEvent, _i32.AuthState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i33.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i33.Future<void>.value(),
        returnValueForMissingStub: _i33.Future<void>.value(),
      ) as _i33.Future<void>);

  @override
  void onChange(_i46.Change<_i32.AuthState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
