// Mocks generated by Mockito 5.4.4 from annotations
// in trydos/test/helpers_for_mock_classes/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trydos/core/error/failures.dart' as _i5;
import 'package:trydos/features/authentication/data/models/create_user_response_model.dart'
    as _i6;
import 'package:trydos/features/authentication/data/models/get_user_country_response_model.dart'
    as _i10;
import 'package:trydos/features/authentication/data/models/login_to_chat_response_model.dart'
    as _i7;
import 'package:trydos/features/authentication/data/models/login_to_stories_response_model.dart'
    as _i9;
import 'package:trydos/features/authentication/data/models/send_otp_response_model.dart'
    as _i12;
import 'package:trydos/features/authentication/data/models/store_fcm_token_response_model.dart'
    as _i11;
import 'package:trydos/features/authentication/data/models/verify_guest_phone_response_model.dart'
    as _i13;
import 'package:trydos/features/authentication/data/models/verify_otp_sign_up_and_in_response_model.dart'
    as _i8;
import 'package:trydos/features/authentication/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CreateUserResponseModel>> createUser(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [params],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i6.CreateUserResponseModel>>.value(
            _FakeEither_0<_i5.Failure, _i6.CreateUserResponseModel>(
          this,
          Invocation.method(
            #createUser,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CreateUserResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.LoginToChatResponseModel>> loginToChat(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginToChat,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, _i7.LoginToChatResponseModel>>.value(
            _FakeEither_0<_i5.Failure, _i7.LoginToChatResponseModel>(
          this,
          Invocation.method(
            #loginToChat,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.LoginToChatResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>
      loginToMarket(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #loginToMarket,
              [params],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.Failure,
                    _i8.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #loginToMarket,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>
      registerGuest(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #registerGuest,
              [params],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.Failure,
                    _i8.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #registerGuest,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i9.LoginToStoriesResponseModel>> loginToStories(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginToStories,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, _i9.LoginToStoriesResponseModel>>.value(
            _FakeEither_0<_i5.Failure, _i9.LoginToStoriesResponseModel>(
          this,
          Invocation.method(
            #loginToStories,
            [params],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, _i9.LoginToStoriesResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> updateName(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #updateName,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> updateChatUserName(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatUserName,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #updateChatUserName,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> updateStoriesUser(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStoriesUser,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #updateStoriesUser,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteFcmToken(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFcmToken,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteFcmToken,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.User>> getCustomerInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomerInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.User>>.value(
            _FakeEither_0<_i5.Failure, _i8.User>(
          this,
          Invocation.method(
            #getCustomerInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.GetUserCountryResponseModel>>
      getUserCountry() => (super.noSuchMethod(
            Invocation.method(
              #getUserCountry,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i10.GetUserCountryResponseModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.GetUserCountryResponseModel>(
              this,
              Invocation.method(
                #getUserCountry,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i10.GetUserCountryResponseModel>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i11.StoreFcmTokenResponseModel>> storeFcmToken(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeFcmToken,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, _i11.StoreFcmTokenResponseModel>>.value(
            _FakeEither_0<_i5.Failure, _i11.StoreFcmTokenResponseModel>(
          this,
          Invocation.method(
            #storeFcmToken,
            [params],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, _i11.StoreFcmTokenResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.SendOtpResponseModel>> sendOtp(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [params],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i12.SendOtpResponseModel>>.value(
            _FakeEither_0<_i5.Failure, _i12.SendOtpResponseModel>(
          this,
          Invocation.method(
            #sendOtp,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i12.SendOtpResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>
      verifyOtpSignIn(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #verifyOtpSignIn,
              [params],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.Failure,
                    _i8.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #verifyOtpSignIn,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>
      verifyOtpSignUp(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #verifyOtpSignUp,
              [params],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.Failure,
                    _i8.VerifyOtpSignUpAndInResponseModel>>.value(_FakeEither_0<
                _i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>(
              this,
              Invocation.method(
                #verifyOtpSignUp,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i8.VerifyOtpSignUpAndInResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.VerifyGuestPhoneResponseModel>>
      verifyGuestPhone(Map<String, dynamic>? params) => (super.noSuchMethod(
            Invocation.method(
              #verifyGuestPhone,
              [params],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i13.VerifyGuestPhoneResponseModel>>.value(
                _FakeEither_0<_i5.Failure, _i13.VerifyGuestPhoneResponseModel>(
              this,
              Invocation.method(
                #verifyGuestPhone,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i13.VerifyGuestPhoneResponseModel>>);
}
