name: Deploy to Play Store Internal

on:
  push:
    branches:
      - dev_new  # سيشتغل هذا الـ Pipeline تلقائياً عندما ترفع كود لفرع main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود من المستودع
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. تثبيت الجافا
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تثبيت فلاتر
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. تحميل مكاتب فلاتر
      - name: Install Dependencies
        run: flutter pub get

      # 5. تشغيل اختبارات فلاتر (تم تعطيلها مؤقتاً)
      # - name: Run Flutter Tests
      #   run: flutter test

      # 6. تحويل النص المشفر إلى ملف مفتاح حقيقي داخل سيرفر GitHub (تم ضبط المسار ليتوافق مع الـ gradle)
      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > upload-keystore.jks

      # 7. بناء التطبيق وتمرير أرقام الإصدارات تلقائياً
      - name: Build App Bundle
        env:
          ANDROID_KEYSTORE_PATH: "upload-keystore.jks"
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          BUILD_NUM=$((${{ github.run_number }} + 7))
          flutter build appbundle --release --build-number=$BUILD_NUM

      # 8. الرفع تلقائياً إلى المسار الداخلي بالمتجر (Internal Testing)
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON_KEY }}
          packageName: com.trydos.www
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          tracks: internal
          status: completed